name: Maven-Build
runs:
  using: "composite"
  steps:
#   - name: Checkout Github Action
#     uses: actions/checkout@v3
  - name: Maven Build
    run:  mvn package
    shell: bash
  - name: Calling file
    run:  cat hello.txt
    shell: bash
