name: Maven-version
runs:
  using: "composite"
  steps:
  - name: Checkout Github Action
    uses: actions/checkout@v3
  - name: Maven Versioning
    uses: ./.github/workflows/version/
  - name: Maven Build
    uses: ./.github/workflows/Build/ 
   
  
