name: Maven-version
runs:
  using: "composite"
  steps:
#   - name: Checkout Github Action
#     uses: actions/checkout@v3
  - name: Maven Versioning
    uses: docker://maven:3.3-jdk-8
    with:
      entrypoint: /bin/sh/
      args: mvn clean versions:set -DnewVersion=0.4.0

#version
