name: Maven-version
runs:
  using: "composite"
  steps:
#   - name: Checkout Github Action
#     uses: actions/checkout@v3
  - name: Maven Versioning
    run: mvn clean versions:set -DnewVersion=0.4.0
    shell: bash
  - name: Listing Files
    run: ls -l
    shell: bash
  - name: Path
    run: pwd
    shell: bash
  - run: mkdir -p /__w/java-hello-world-with-maven/artifact_dir
    shell: bash
  - name: Listing Files
    run: ls -l
    shell: bash
  - run: cp -r  *  /__w/java-hello-world-with-maven/artifact_dir/
    shell: bash
  - uses: actions/upload-artifact@v3
    with:
      name: my-artifact
      path: artifact_dir
