name: Maven-version
maven:
  image: maven:3.3-jdk-8
runs:
  using: "composite"
  steps:
#   - name: Checkout Github Action
#     uses: actions/checkout@v3
  - name: Maven Versioning
    run: mvn clean versions:set -DnewVersion=0.4.0
    shell: bash
  - name: Maven Built
    run: mvn clean package
    shell: bash 
  - uses: actions/checkout@v2
  - run: mkdir -p path/to/artifact
    shell: bash
  - run: echo hello > path/to/artifact/test.txt
    shell: bash
  - uses: actions/upload-artifact@v3
    with:
      name: my-artifact
      path: path/to/artifact/test.txt

    
