name: Maven-version
on:
  push:
    branches: [ master ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: maven:3.3-jdk-8
      volumes:
        - /home/ubuntu/:/__w/java-hello-world-with-maven/java-hello-world-with-maven
    steps:
    - name: Checkout Github Action
      uses: actions/checkout@v3
    - name: Maven Versioning
      run: mvn clean versions:set -DnewVersion=0.4.0
    - name: Maven Built
      run: mvn clean package
    - name: 'Upload Artifact'
      uses: actions/checkout@v2
    - run: mkdir -p path/to/artifact
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: path/to/artifact
    - name: 'Download Artifact'
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: my-artifact
        path: path/to/artifact
 
