name: Maven-version
on:
  push:
    branches: [ master ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: maven:3.3-jdk-8
      volumes:
        - /home/ubuntu/:/__w/java-hello-world-with-maven/java-hello-world-with-maven
    steps:
    - name: Checkout Github Action
      uses: actions/checkout@v3
    - name: Build with Maven
      run: mvn clean versions:set -DnewVersion=0.4.0
