name: Maven versoning
on:
  push:
    branches: [ master ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.6-jdk-11
    steps:
      - name: Checkout Github Action
        uses: action/checkout/master
