name: Merge to feature

# Workflow for push on a feature branch
on:
  push:
    branches:
      - step-container
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
    - name: Checkout  
      uses: actions/checkout@v2
    - name: Calling Composite action file  
      uses: ./.github/workflows/
      with:
        image: maven:3.3-jdk-8
    - name: Calling composite for Maven Built
      uses: ./.github/actions/
      with:
        image: maven:3.3-jdk-8
        
#Testing
