name: Merge to feature

# Workflow for push on a feature branch
on:
  push:
    branches:
      - workspace-step
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Calling PR_template for Containazied version and Build
      uses: Xoriant123/gh-composite1@PR-template
#TEst1111
