name: Merge to feature

# Workflow for push on a feature branch
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Calling PR_template for Containazied version and Build
      uses: ./.github/workflows/PR-template/
