name: Merge to feature

# Workflow for push on a feature branch
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
    - name: Checkout  
      uses: actions/checkout@v2
    - name: Calling Composite action file  
      uses: ./.github/workflows/
      with:
        image: maven:3.3-jdk-8
#Test
