name: Merge to feature

# Workflow for push on a feature branch
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
    - name: Checkout  
      uses: actions/checkout@v2
    - name: Calling Composite action file  
      uses: ./.github/workflows/
  download:
     runs-on: [ ubuntu-latest ]
     needs: build
     steps:  
      - name: 'Download artifact'
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/

#Test1111
