name: Merge to feature

# Workflow for push on a feature branch
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    container:
      image: maven:3.3-jdk-8
    steps:
    - name: Checkout  
      uses: actions/checkout@v2
    - name: Calling Composite action file  
      uses: ./.github/workflows/
    - name: Cmd run
      run: ls -l
      shell: bash
  Build-download:
     runs-on: [ ubuntu-latest ]
     container:
       image: maven:3.3-jdk-8
     needs: build
     steps:  
      - name: 'Download artifact'
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact
      - name: Maven Built
        run: mvn package
        shell: bash 
        
#Testing
