name: Merge to feature

# Workflow for push on a feature branch
on:
  push:
    branches:
      - workspace-step
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #- name: Calling PR_template for Containazied version and Build
     # uses: Xoriant123/gh-composite1@PR-template
      
- name: Maven Versioning
    uses: docker://maven:3.8.6-jdk-11
    with:
      entrypoint: /usr/local/bin/mvn-entrypoint.sh
      args: |
        mvn versions:set -DnewVersion=0.4.0
        mvn clean package
#TEst121
